spring.application.name=MVC
spring.mongodb.uri=mongodb://localhost:27017/userdb
spring.data.mongodb.database=userdb

# Log Spring Data MongoDB queries
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG